### ISSUE TITLE
Задание 2

### ISSUE THREAD

**Issue by ala-n** [XKiriosX/stud-practice#2]
Начало было положено не плохое, но итог не агонь )

Во первых Pull Request

Теперь по мокапу:
Идеальный мокап - мокап после которого не надо лезть глубоко в ТЗ. Мокап это не дизайн и не так называемые рэдлайны.
1) Фильтры, верствльшику не понятно где они и как выглядят.
2) Дата публикации, кроткое описание поста не найдены
3) страница "Ошибка" не найдена
4) страница добавления поста не найдена
5) кнопки "редактировать", "удалить" не найдены
6) к сайдбару "Автризация" не плохо бы тайтл (Это уже UX заметка)
7) комментарии должны отображать все что непонятно визуально.
Например какие контролы ведут на те или иные виды страницы (если это не очевидно, как мне сейчас с "Авторизацией")

Важно в этом задании: максимально покрыть ТЗ, не натворить несоответствий и непоняток

**Comment by XKiriosX** [comment]
@ala-n , Наконец-то руки дошли до аплоуда финального прототипа. Сорри, что так долго :)
Branch: mockup

**Comment by ala-n** [comment]
Moved to https://github.com/XKiriosX/stud-practice/pull/3 discussion.
